In [1]:
import pandas as pd

In [9]:
contests = pd.read_csv("convertcsv.csv")

In [14]:
contests

,id_competition,id_fight,id_person_blue,id_person_white,id_winner,is_finished,round,duration,ippon,waza,...,country_short_blue,id_country_blue,picture_folder_1,picture_filename_1,picture_folder_2,picture_filename_2,media,rank_name,personal_picture_white,personal_picture_blue
0,1527,363610,2673,10710,2673,1,0,00:00:00,NaN,NaN,...,ARG,77,/2019/08/,10710_1565029233.jpg,/2019/04/,2673_1554972035.jpg,NaN,African Open,https://www.judobase.org/files/persons//2019/0...,https://www.judobase.org/files/persons//2019/0...
1,1555,363140,13763,8652,8652,1,0,00:00:00,NaN,NaN,...,VAN,287,/2018/03/,8652_1521465839.jpg,/2018/03/,13763_1521459688.jpg,NaN,Oceanian Open,https://www.judobase.org/files/persons//2018/0...,https://www.judobase.org/files/persons//2018/0...
2,1577,383335,9904,12367,12367,1,0,00:00:00,NaN,NaN,...,SAM,167,/2019/09/,12367_1568391890.jpg,/2019/09/,9904_1568391924.jpg,NaN,Oceanian Championships,https://www.judobase.org/files/persons//2019/0...,https://www.judobase.org/files/persons//2019/0...
3,1448,321375,2673,925,2673,1,0,00:00:00,NaN,NaN,...,ARG,77,/imported/,1266_0923100004905.jpg,/2019/04/,2673_1554972035.jpg,NaN,NaN,https://www.judobase.org/files/persons//import...,https://www.judobase.org/files/persons//2019/0...
4,1715,450501,12236,2673,2673,1,0,00:00:00,NaN,NaN,...,ECU,92,/2019/04/,2673_1554972035.jpg,/2019/07/,12236_1562955984.jpg,NaN,NaN,https://www.judobase.org/files/persons//2019/0...,https://www.judobase.org/files/persons//2019/0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,1601,435710,285,19169,285,1,4,00:00:32,1.0,0.0,...,NED,28,/2021/04/,19169_1618313974.jpg,/2018/12/,285_1544101044.jpg,yt*cHgrwI_oK1o*00:00:11,Grand Slam,https://www.judobase.org/files/persons//2021/0...,https://www.judobase.org/files/persons//2018/1...
346,1586,437636,28416,34569,34569,1,2,00:02:00,1.0,0.0,...,AUS,56,/2019/12/,34569_1575370840.jpg,/2018/12/,28416_1544093604.jpg,NaN,Asian Open,https://www.judobase.org/files/persons//2019/1...,https://www.judobase.org/files/persons//2018/1...
347,1726,465336,52221,34736,52221,1,4,00:01:09,1.0,0.0,...,KUW,87,/2019/04/,34736_1554898182.jpg,/2019/04/,52221_1556624685.jpg,NaN,Asian Championships,https://www.judobase.org/files/persons//2019/0...,https://www.judobase.org/files/persons//2019/0...
348,1759,490587,15224,37516,15224,1,3,00:03:26,1.0,1.0,...,KOR,15,/2019/04/,37516_1556266436.jpg,/2019/07/,15224_1562333621.jpg,NaN,Asian Open,https://www.judobase.org/files/persons//2019/0...,https://www.judobase.org/files/persons//2019/0...
349,1736,495982,49961,40370,40370,1,3,00:05:00,1.0,1.0,...,USA,57,/2019/07/,40370_1563539401.jpg,/2019/04/,49961_1556092810.jpg,NaN,Asian Open,https://www.judobase.org/files/persons//2019/0...,https://www.judobase.org/files/persons//2019/0...

In [17]:
calc_data = contests[["id_person_blue", "id_person_white", "id_winner", "competition_date"]]
calc_data

     id_person_blue  id_person_white  id_winner competition_date
0              2673            10710       2673       2017-11-18
1             13763             8652       8652       2017-11-11
2              9904            12367      12367       2018-04-06
3              2673              925       2673       2017-03-11
4             12236             2673       2673       2019-03-09
..              ...              ...        ...              ...
345             285            19169        285       2018-11-23
346           28416            34569      34569       2018-12-01
347           52221            34736      52221       2019-04-20
348           15224            37516      15224       2019-07-18
349           49961            40370      40370       2019-08-03

[350 rows x 4 columns]

In [20]:
import requests

res = requests.get("https://data.ijf.org/api/get_json?access_token=&params%5Baction%5D=contest.find&params%5B__ust%5D=&params%5Bid_weight%5D=6&params%5Byear%5D=2023&params%5Blimit%5D=1000&params%5Border_by%5D=competition_date", verify=False)